version: "3.8"

services:
  postgres:
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - backend
      - kong

  migrations:
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    depends_on:
      - postgres
    profiles:
      - migrate
    restart: unless-stopped
    networks:
      - kong

  kong:
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - HOST_IP=host.docker.internal
    ports:
      - "8000:8000"
      - "8001:8001"
    restart: unless-stopped
    networks:
      - backend
      - kong

  konga:
    environment:
      NO_AUTH: true
    volumes:
      - .docker/konga/konga.db:/app/kongadata/konga.db
      - konga-data:/app/kongadata
    ports:
      - "1337:1337"
    restart: unless-stopped
    networks:
      - kong

networks:
  backend:
    driver: bridge
  kong:
    driver: bridge

volumes:
  postgres-data:
  konga-data:

